### ISSUE TITLE
Weird stacktrace in File application

### ISSUE THREAD

**Issue by frankrousseau** [cozy/cozy-db#5]
Here is the stacktrace when I run the File application in development mode:

```
Warning : cast ignored property 'tags' { _id: '5265c17aab710ce182973ddfff4dbdc1',
  fn: 'Benjamin André',
  datapoints: [ { name: 'email', type: 'main', value: 'ben@cozycloud.cc' } ],
  note: '',
  tags: [ 'cozy' ],
  docType: 'Contact',
  id: '5265c17aab710ce182973ddfff4dbdc1',
  _attachments: 
   { picture: 
      { content_type: 'application/octet-stream',
        revpos: 4,
        digest: 'md5-GEIFuzq7O0e90cs/6JchrQ==',
        length: 2015,
        stub: true } } } Error
  at exports.castObject.castObject (/home/frankrousseau/mycloud/products/cozy-files/node_modules/cozydb/lib/utils/type_checking.js:119:78)
  at Function.Model.cast (/home/frankrousseau/mycloud/products/cozy-files/node_modules/cozydb/lib/model.js:248:14)
  at Function.module.exports.CozyBackedModel.cast (/home/frankrousseau/mycloud/products/cozy-files/node_modules/cozydb/lib/cozymodel.js:309:57)
  at ClassFromGetModel.Model (/home/frankrousseau/mycloud/products/cozy-files/node_modules/cozydb/lib/model.js:263:24)
  at ClassFromGetModel.CozyBackedModel (/home/frankrousseau/mycloud/products/cozy-files/node_modules/cozydb/lib/cozymodel.js:286:52)
  at new ClassFromGetModel (/home/frankrousseau/mycloud/products/cozy-files/node_modules/cozydb/lib/index.js:48:56)
  at /home/frankrousseau/mycloud/products/cozy-files/node_modules/cozydb/lib/model.js:201:20
  at Array.map (native)
  at /home/frankrousseau/mycloud/products/cozy-files/node_modules/cozydb/lib/model.js:200:41
  at /home/frankrousseau/mycloud/products/cozy-files/node_modules/cozydb/lib/cozymodel.js:254:18
  at parseBody (/home/frankrousseau/mycloud/products/cozy-files/node_modules/cozydb/node_modules/request-json-light/main.js:74:10)
  at IncomingMessage.<anonymous> (/home/frankrousseau/mycloud/products/cozy-files/node_modules/cozydb/node_modules/request-json-light/main.js:99:14)
  at IncomingMessage.EventEmitter.emit (events.js:117:20)
  at _stream_readable.js:920:16
  at process._tickCallback (node.js:415:13)
```

**Comment by aenario** [comment]
This is a warning because the cozy-clearance contact shema do not have a tags field, so when it parse a contact from the DS, it ignore the tags attribute. Jugglingdb would have silently ignored it. 

I will remove this warning when the switch to cozydb is complete for most cozy apps, in the meantime, we can add the tags field in cozy-clearance.

**Comment by frankrousseau** [comment]
ok
